server:
  port: 8001
spring:
  application:
    name: eureka
  security:
    user:
      name: itzhiya
      password: itzhiya
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:8005/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


